
package br.com.fuctura.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MunicipiosWSImplService", targetNamespace = "http://impl.webservices.fuctura.com.br/", wsdlLocation = "http://soap-sample.herokuapp.com/municipios?wsdl")
public class MunicipiosWSImplService
    extends Service
{

    private final static URL MUNICIPIOSWSIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.com.fuctura.webservices.MunicipiosWSImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.com.fuctura.webservices.MunicipiosWSImplService.class.getResource(".");
            url = new URL(baseUrl, "http://soap-sample.herokuapp.com/municipios?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://soap-sample.herokuapp.com/municipios?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MUNICIPIOSWSIMPLSERVICE_WSDL_LOCATION = url;
    }

    public MunicipiosWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MunicipiosWSImplService() {
        super(MUNICIPIOSWSIMPLSERVICE_WSDL_LOCATION, new QName("http://impl.webservices.fuctura.com.br/", "MunicipiosWSImplService"));
    }

    /**
     * 
     * @return
     *     returns MunicipiosWS
     */
    @WebEndpoint(name = "MunicipiosWSImplPort")
    public MunicipiosWS getMunicipiosWSImplPort() {
        return super.getPort(new QName("http://impl.webservices.fuctura.com.br/", "MunicipiosWSImplPort"), MunicipiosWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MunicipiosWS
     */
    @WebEndpoint(name = "MunicipiosWSImplPort")
    public MunicipiosWS getMunicipiosWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.webservices.fuctura.com.br/", "MunicipiosWSImplPort"), MunicipiosWS.class, features);
    }

}
