
package br.com.fuctura.webservices;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MunicipiosWS", targetNamespace = "http://webservices.fuctura.com.br/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MunicipiosWS {


    /**
     * 
     * @return
     *     returns br.com.fuctura.webservices.Municipios
     */
    @WebMethod
    @WebResult(partName = "return")
    public Municipios listar();

}
